### ISSUE TITLE
AttributeError: 'DciJob' object has no attribute 'team_id'

### ISSUE THREAD

**Issue by goneri** [redhat-cip/dci-ansible-agent#12]
failure.yml triggers an error with dci_job.

```
TASK [include] ****************************************************************************************************************************************************
task path: /usr/share/dci-ansible-agent/dci-ansible-agent.yml:250
skipping: [undercloud] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}

TASK [dci_job] ****************************************************************************************************************************************************
task path: /usr/share/dci-ansible-agent/plays/failure.yml:2
Using module file /usr/share/dci/modules/dci_job.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: dci-ansible-agent
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/dci-ansible-agent/.ansible/tmp/ansible-tmp-1516301835.03-252666116667992 `" && echo ansible-tmp-1516301835.03-252666116667992="` echo /var/lib/dci-ansible-agent/.ansible/tmp/ansible-tmp-1516301835.03-252666116667992 `" ) && sleep 0'
<localhost> PUT /tmp/tmpNXj4F7 TO /var/lib/dci-ansible-agent/.ansible/tmp/ansible-tmp-1516301835.03-252666116667992/dci_job.py
<localhost> EXEC /bin/sh -c 'chmod u+x /var/lib/dci-ansible-agent/.ansible/tmp/ansible-tmp-1516301835.03-252666116667992/ /var/lib/dci-ansible-agent/.ansible/tmp/ansible-tmp-1516301835.03-252666116667992/dci_job.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /var/lib/dci-ansible-agent/.ansible/tmp/ansible-tmp-1516301835.03-252666116667992/dci_job.py; rm -rf "/var/lib/dci-ansible-agent/.ansible/tmp/ansible-tmp-1516301835.03-252666116667992/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_qJHbag/ansible_module_dci_job.py", line 265, in <module>
    main()
  File "/tmp/ansible_qJHbag/ansible_module_dci_job.py", line 245, in main
    http_response = run_action_func(action_func, context, module)
  File "/tmp/ansible_qJHbag/ansible_modlib.zip/ansible/module_utils/common.py", line 72, in run_action_func
  File "/tmp/ansible_qJHbag/ansible_modlib.zip/ansible/module_utils/dci_base.py", line 104, in do_update
AttributeError: 'DciJob' object has no attribute 'team_id'

fatal: [undercloud -> localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_qJHbag/ansible_module_dci_job.py\", line 265, in <module>\n    main()\n  File \"/tmp/ansible_qJHbag/ansible_module_dci_job.py\", line 245, in main\n    http_response = run_action_func(action_func, context, module)\n  File \"/tmp/ansible_qJHbag/ansible_modlib.zip/ansible/module_utils/common.py\", line 72, in run_action_func\n  File \"/tmp/ansible_qJHbag/ansible_modlib.zip/ansible/module_utils/dci_base.py\", line 104, in do_update\nAttributeError: 'DciJob' object has no attribute 'team_id'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
...ignoring

TASK [fail] *******************************************************************************************************************************************************
task path: /usr/share/dci-ansible-agent/plays/failure.yml:6
fatal: [undercloud -> localhost]: FAILED! => {
    "changed": false, 
    "msg": "Something went wrong during the post-run. Review the log at: https://www.distributed-ci.io/#!/jobs/86b3b1b7-68ec-424c-9bd1-95c3f3cc3cc0/jobStates"
}
```

```
python2-dciclient-0.5-1.201801111319git88a75a1f.el7.centos.noarch
dci-ansible-0.0.201801101536git3ea7f374-1.el7.centos.noarch
dci-release-0.1-4.el7.centos.noarch
dci-agent-0.0.201703212113git9c73374c-1.el7.centos.noarch
python2-dciauth-2.0.2-1.el7.centos.noarch
dci-ansible-agent-0.0.201801092055git64962e32-1.el7.centos.noarch
```

**Comment by goneri** [comment]
@Spredzy, it looks like the update through dci_job is broken.
