### ISSUE TITLE
DCI:Tempest test case execution stuck for hours than expected

### ISSUE THREAD

**Issue by goneri** [redhat-cip/dci-ansible-agent#19]
Imported from: https://bugzilla.redhat.com/show_bug.cgi?id=1588914

Description of problem:

Tempest test execution stuck after executing some test cases:

https://www.distributed-ci.io/jobs/354da846-abfd-478f-a798-6c64251817fd/jobStates

The last message from UI: 
----- 

newton/validate-tempest : Install openstack services tempest pluginspost-run
All items completed
All items completed (changed: True)

Journelctl Logs:
====

Jun 07 16:46:04 5a11s38-node4 ansible-playbook[36456]: TASK [newton/validate-tempest : Install openstack services tempest plugins] ****
Jun 07 16:46:04 5a11s38-node4 ansible-playbook[36456]: task path: /usr/share/dci-ansible-agent/roles/newton/validate-tempest/tasks/pre-tempest.yml:32
Jun 07 16:47:40 5a11s38-node4 ansible-playbook[36456]: changed: [undercloud] => (item=[u'openstack-tempest-all']) => {"changed": true, "item": ["openstack-tempest-all"], "msg": "", "rc": 0, "results": e
Jun 07 16:47:40 5a11s38-node4 ansible-playbook[36456]: sts.noarch 1:3.0.0-4.el7ost                                    \n  t1lib.x86_64 0:5.1.2-14.el7                                                   \}
Jun 07 16:47:41 5a11s38-node4 ansible-playbook[36456]: TASK [newton/validate-tempest : Copying bugcheck files] ************************
Jun 07 16:47:41 5a11s38-node4 ansible-playbook[36456]: task path: /usr/share/dci-ansible-agent/roles/newton/validate-tempest/tasks/pre-tempest.yml:40
Jun 07 16:47:41 5a11s38-node4 ansible-playbook[36456]: skipping: [undercloud] => {"changed": false, "skip_reason": "Conditional result was False"}
Jun 07 16:47:41 5a11s38-node4 ansible-playbook[36456]: TASK [newton/validate-tempest : Copying skip file] *****************************
Jun 07 16:47:41 5a11s38-node4 ansible-playbook[36456]: task path: /usr/share/dci-ansible-agent/roles/newton/validate-tempest/tasks/pre-tempest.yml:46
Jun 07 16:47:41 5a11s38-node4 ansible-playbook[36456]: skipping: [undercloud] => {"changed": false, "skip_reason": "Conditional result was False"}
Jun 07 16:47:41 5a11s38-node4 ansible-playbook[36456]: TASK [newton/validate-tempest : Setting virtualenv] ****************************
Jun 07 16:47:41 5a11s38-node4 ansible-playbook[36456]: task path: /usr/share/dci-ansible-agent/roles/newton/validate-tempest/tasks/pre-tempest.yml:52
Jun 07 16:47:41 5a11s38-node4 ansible-playbook[36456]: skipping: [undercloud] => {"changed": false, "skip_reason": "Conditional result was False"}
Jun 07 16:47:41 5a11s38-node4 ansible-playbook[36456]: TASK [newton/validate-tempest : Installing requirements] ***********************
Jun 07 16:47:41 5a11s38-node4 ansible-playbook[36456]: task path: /usr/share/dci-ansible-agent/roles/newton/validate-tempest/tasks/pre-tempest.yml:56
Jun 07 16:47:41 5a11s38-node4 ansible-playbook[36456]: skipping: [undercloud] => {"changed": false, "skip_reason": "Conditional result was False"}
Jun 07 16:47:41 5a11s38-node4 ansible-playbook[36456]: TASK [newton/validate-tempest : Verifying bugs in bugzilla and launchpad and generating skip file] ***
Jun 07 16:47:41 5a11s38-node4 ansible-playbook[36456]: task path: /usr/share/dci-ansible-agent/roles/newton/validate-tempest/tasks/pre-tempest.yml:61
Jun 07 16:47:41 5a11s38-node4 ansible-playbook[36456]: skipping: [undercloud] => {"changed": false, "skip_reason": "Conditional result was False"}
Jun 07 16:47:41 5a11s38-node4 ansible-playbook[36456]: TASK [newton/validate-tempest : Execute tempest] *******************************
Jun 07 16:47:41 5a11s38-node4 ansible-playbook[36456]: task path: /usr/share/dci-ansible-agent/roles/newton/validate-tempest/tasks/run-tempest.yml:2

tempest_output.log:
======= 

[stack@undercloud ~]$ tail -f tempest_output.log
2018-06-07 22:18:28 | {1} tempest.scenario.gnocchi.test.live_post_some_measures_to_the_metric_on_myresource.test_request [120.004209s] ... FAILED
2018-06-08 00:19:29 | {1} tempest.scenario.gnocchi.test.live_get_myresource_measures_with_poll.test_request [7260.271934s] ... FAILED
2018-06-08 00:21:29 | {1} tempest.scenario.gnocchi.test.live_post_some_more_measures_to_the_metric_on_myresource.test_request [120.004467s] ... FAILED
2018-06-08 00:23:29 | {1} tempest.scenario.gnocchi.test.live_get_myresource_measures_with_refresh.test_request [120.004453s] ... FAILED
2018-06-08 00:25:29 | {1} tempest.scenario.gnocchi.test.live_typo_of_search.test_request [120.004088s] ... FAILED

Version-Release number of selected component (if applicable):

How reproducible:

Steps to Reproduce:
1.
2.
3.

Actual results:

Expected results:

test cases should run without delay
Additional info:

**Comment by goneri** [comment]
```
2018-06-08 07:00:30 | tempest.scenario.gnocchi.test.live_get_myresource_measures_with_poll.test_request
2018-06-08 07:00:30 | ---------------------------------------------------------------------------------
2018-06-08 07:00:30 |
2018-06-08 07:00:30 | Captured traceback:
2018-06-08 07:00:30 | ~~~~~~~~~~~~~~~~~~~
2018-06-08 07:00:30 |     Traceback (most recent call last):
2018-06-08 07:00:30 |       File "/usr/lib/python2.7/site-packages/gabbi/case.py", line 92, in wrapper
2018-06-08 07:00:30 |         func(self)
2018-06-08 07:00:30 |       File "/usr/lib/python2.7/site-packages/gabbi/case.py", line 140, in test_request
2018-06-08 07:00:30 |         self._run_test()
2018-06-08 07:00:30 |       File "/usr/lib/python2.7/site-packages/gabbi/case.py", line 388, in _run_test
2018-06-08 07:00:30 |         raise failure
2018-06-08 07:00:30 |     AssertionError: '504' not found in ['200'], response:
2018-06-08 07:00:30 |     <html><body><h1>504 Gateway Time-out</h1>
2018-06-08 07:00:30 |     The server didn't respond in time.
2018-06-08 07:00:30 |     </body></html>
```

The error is not related to DCI and I'm surprised because the previous runs were more faster.

**Comment by dsavineau** [comment]
Tempest execution isn't stuck but takes a lot of time on two gnocchi tests (for some reason there's no timeout)
```
<testcase classname="tempest.scenario.gnocchi.test.live_get_myresource_measures_with_poll" name="test_request" time="7260.272">
<failure type="testtools.testresult.real._StringException">Traceback (most recent call last):
testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gabbi/case.py", line 92, in wrapper
    func(self)
  File "/usr/lib/python2.7/site-packages/gabbi/case.py", line 140, in test_request
    self._run_test()
  File "/usr/lib/python2.7/site-packages/gabbi/case.py", line 388, in _run_test
    raise failure
AssertionError: '504' not found in ['200'], response:
&lt;html>&lt;body>&lt;h1>504 Gateway Time-out&lt;/h1>
The server didn't respond in time.
&lt;/body>&lt;/html>

<testcase classname="tempest.scenario.gnocchi.test.live_delete_single_archive_policy_cleanup" name="test_request" time="21762.470">
<failure type="testtools.testresult.real._StringException">Traceback (most recent call last):
testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gabbi/case.py", line 92, in wrapper
    func(self)
  File "/usr/lib/python2.7/site-packages/gabbi/case.py", line 140, in test_request
    self._run_test()
  File "/usr/lib/python2.7/site-packages/gabbi/case.py", line 377, in _run_test
    redirect=test['redirects'])
  File "/usr/lib/python2.7/site-packages/gabbi/case.py", line 322, in _run_request
    redirect=redirect
  File "/usr/lib/python2.7/site-packages/gabbi/httpclient.py", line 43, in request
    method, absolute_uri, body=body, headers=headers, retries=retry)
  File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 69, in request
    **urlopen_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 90, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/poolmanager.py", line 248, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python2.7/site-packages/urllib3/util/retry.py", line 238, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib64/python2.7/httplib.py", line 1113, in getresponse
    response.begin()
  File "/usr/lib64/python2.7/httplib.py", line 444, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.7/httplib.py", line 408, in _read_status
    raise BadStatusLine(line)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine("''",))
```

That's 8h for only two tests.

The root cause of this is that redis is down (used by gnocchi) :
```
# pcs status |grep redis -A1
 Master/Slave Set: redis-master [redis]
     Stopped: [ overcloud-controller-0 ]
--
* redis_start_0 on overcloud-controller-0 'not running' (7): call=65, status=complete, exitreason='',
    last-rc-change='Thu Jun  7 23:00:24 2018', queued=0ms, exec=153ms
```

There's probably a missing configuration on the setup because redis fails to start due to the bind address/port already used by haproxy.

```
# netstat -lntup|grep 6379
tcp        0      0 10.0.0.20:6379          0.0.0.0:*               LISTEN      196785/haproxy

# /etc/haproxy/haproxy.cfg
listen redis
  bind 10.0.0.20:6379 transparent
  (...)
  server overcloud-controller-0.internalapi.localdomain 10.0.0.20:6379 check fall 5 inter 2000 rise 2

# /etc/redis.conf
bind 10.0.0.20

# /var/log/redis/redis.log
# Creating Server TCP listening socket 10.0.0.20:6379: listen: Address already in use
```

So the same ipaddr 10.0.0.20 is used for both haproxy and redis backend. I think it's more on the frontend side that the ip is wrong because 10.0.0.20 seems to be defined as a static value for the controller node.

```
# environments/ips-from-pool-all.yaml
parameter_defaults:
  ControllerIPs:
    internal_api:
    - 10.0.0.20
```

But the RedisVIP isn't defined anywhere so it takes a random ipaddr from the internal api sunet pool allocation

```
$ neutron subnet-show internal_api_subnet -c allocation_pools
+------------------+---------------------------------------------+
| Field            | Value                                       |
+------------------+---------------------------------------------+
| allocation_pools | {"start": "10.0.0.11", "end": "10.0.0.200"} |
+------------------+---------------------------------------------+

$ neutron port-show redis_virtual_ip -c fixed_ips
+-----------+----------------------------------------------------------------------------------+
| Field     | Value                                                                            |
+-----------+----------------------------------------------------------------------------------+
| fixed_ips | {"subnet_id": "845566fc-0063-498b-8bc5-5f48d90ce5c8", "ip_address": "10.0.0.20"} |
+-----------+----------------------------------------------------------------------------------+
```
Unfortunately the controller static ip aren't exclude from the allocation_pools so in some case you can have the same ipaddr allocated for Redis VIP (randomly) and Controller node 0 (fixed).

The best solution could be to set the Redis VIP (RedisVirtualFixedIPs in the templates) statically like it's done for the internal and public networks

```
$ grep -A1 VirtualFixedIPs environments/ips-from-pool-all.yaml
  PublicVirtualFixedIPs:
    - ip_address: 192.168.122.100
--
  InternalApiVirtualFixedIPs:
    - ip_address: 10.0.0.10
```
